name: Release
on:
  release:
    types: [edited, published]

jobs:
  notify-release:
    name: Notify release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@74c3d60f5a28f358ccf241a00c9021ea16f0569f # v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Notify Slack
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": ":rocket-snail: *NEW VERSION*: ${{ steps.get_release.outputs.tag_name }} - ${{ steps.get_release.outputs.html_url }}"
            }
