name: Release
on:
  release:
    types: [edited, published]

jobs:
  notify-release:
    name: Notify release
    runs-on: ubuntu-latest
    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Notify Slack
        uses: archive/github-actions-slack@v1.1.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: "#team-tornado-deployments"
          slack-text: |
            :rocket-snail: *NEW VERSION*: ${{ steps.get_release.outputs.tag_name }} - ${{ steps.get_release.outputs.html_url }}
